os: linux
dist: focal
language: shell

addons:
  apt:
    packages:
    - git 
    - wget 
    - flex 
    - bison
    - gperf
    - python3
    - python3-pip
    - python3-setuptools
    - cmake
    - ninja-build
    - ccache
    - libffi-dev
    - libssl-dev
    - dfu-util
    - libusb-1.0-0
install:
  - mkdir ~/esp
  - cd ~/esp
  - git clone -b release/v4.4 --recursive https://github.com/espressif/esp-idf.git
  - cd ~/esp/esp-idf
  - ./install.sh
  - . ~/esp/esp-idf/export.sh

script:
  - cd $TRAVIS_BUILD_DIR
  - idf.py reconfigure
  - idf.py build
  - idf.py size

branches:
  only:
  - main